[build]
  command = "node ./scripts/create-env.js && npm install && npm run build-only"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
